### ISSUE TITLE
Meeting Recordings

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#1]
@stanblum has suggested that we record future meetings and save the recordings for a short period of time (2 months) so that those who cannot attend either monthly meeting can view the meeting(s) they missed. Please respond to this issue and indicate your agreement/opposition to this.

**Comment by tucotuco** [comment]
I agree.

**Comment by Jegelewicz** [comment]
Meeting recordings when made are in the Google Drive
