### ISSUE TITLE
Make URLs on Group Charter site clickable

### ISSUE THREAD

**Issue by cboelling** [tdwg/material-sample#13]
There are a number of URLs on https://www.tdwg.org/community/osr/material-sample/ which aren't displayed as clickable hyperlinks at the moment - may be this could be updated for more convenient use.

**Comment by Jegelewicz** [comment]
I added hyperlinks, but I cannot update. See pull request - https://github.com/tdwg/website/pull/446

**Comment by stanblum** [comment]
Merged.  Done.
