### ISSUE TITLE
Suggested new term - parentMaterialSampleID

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#15]
From [New Term - parentMaterialSampleID](https://github.com/tdwg/dwc/issues/344)

_Originally posted by @Jegelewicz in https://github.com/tdwg/material-sample/issues/2#issuecomment-937790555_

**Comment by dr-shorthair** [comment]
There will be other relationships. It will be unwieldy to enumerate them all with specific properties or links. So you might need an association-class/link-table so each relation can be annotated with a 'type of relationship' or 'role' value.

**Comment by dagendresen** [comment]
@dr-shorthair such as the [dwc:ResourceRelationship](https://dwc.tdwg.org/terms/#resourcerelationship) ?

**Comment by Jegelewicz** [comment]
closing as out of scope and because relating relationships could be made between materialEntityID and/or materialSampleID
