### ISSUE TITLE
material samples that are NOT part of a collection

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#30]
Sort of! As I outlined at our last meeting I do not feel these cover material samples that are NOT part of a collection very well such as eDNA water or soil samples that are discarded after being processed and not stored in a physical collection.

This is what I get concerned about when parts of the community hone in on one particular piece without considering the larger community that would have to shoehorn themselves into something that wasn't developed with that particular use case in mind.

_Originally posted by @albenson-usgs in https://github.com/tdwg/material-sample/issues/29#issuecomment-1323962757_

**Comment by Jegelewicz** [comment]
> cover material samples that are NOT part of a collection very well such as eDNA water or soil samples that are discarded after being processed and not stored in a physical collection.

Can you offer some suggestions for how we should do that? LatimerCore is about describing collections, and I think we need to make sure we are facilitating that, but what needs to be added for your use case? I have trouble understanding exactly what you would like to see!

**Comment by albenson-usgs** [comment]
I don't think Latimer Core is the answer for all material samples. It's like how not all squares are rectangles. Not all material samples are collections. This community developed those terms and definitions with that specific focus in mind. I do not think there is a way to modified what they have done and expand it to include material samples that are not part of collections.

**Comment by albenson-usgs** [comment]
I think what's currently happening already works ok for eDNA. I simply use `basisOfRecord` = MaterialSample. My interest in the task group is in ensuring I still understand and have a logical way to populate `basisOfRecord` for eDNA datasets (or whatever the replacement ends up being) that come to me through GBIF.us or OBIS-USA and making sure eDNA datasets are not lost as a use case in the modifications that happen to MaterialSample terms. At this point, I don't understand what's being proposed so I can't speak to what needs to be facilitated. Does the help clarify?

**Comment by Jegelewicz** [comment]
closing as out of scope
