### ISSUE TITLE
materialEntity: 'identified as persistent'

### ISSUE THREAD

**Issue by smrgeoinfo** [tdwg/material-sample#34]
The definition of materialEntity needs clarification. What does "An entity that can be **identified as persistent**" mean?

I think (hope) what is intended is 1) that the entity can be identified and 2) that the entity exists for some period of time (is persistent).  

the definition broken down:
1. materialEntity is a kind of entity (genera)
differentia:
2. it is an entity that can be identified
3. it is an entity that exists for some period of time
4. it is an entity that consists in whole or in part of physical matter while it exists.

is physical matter a materialEntity?...

**Comment by tucotuco** [comment]
@smrgeoinfo  I like your broken down definition. Adapting it to the [new proposal for MaterialEntity](https://github.com/tdwg/dwc/issues/426), I suggest replacing the current

"An entity that can be identified as persistent through some period of time during which it consists in whole or in part of physical matter."

with

"A kind of entity that can be distinguished from other entities by an identifier, that exists for some period of time, and that consists in whole or in part of physical matter while it exists."

> is physical matter a materialEntity?...

I find it difficult to nail down what the question means. I would say that an instance of physical matter that you can give an identifier to that distinguishes if from other physical matter would be an instance of `MaterialEntity`. In other words, if you had some stuff in a tube and had no idea what it was, other than physical stuff, you could put an identifier on that and call it "physical matter" for lack of anything more descriptive.

**Comment by Jegelewicz** [comment]
Can we simplify?

Something that can be assigned an identifier, that exists for some period of time, and that consists in whole or in part of physical matter while it exists.

**Comment by dagendresen** [comment]
Or maybe

Material entities `can be identified`, exists for some period of time, and consists in whole or in part of physical matter while it exists.

See also [BFO_0000040](http://purl.obolibrary.org/obo/BFO_0000040)
> A material entity is an independent continuant that has some portion of matter as proper or improper continuant part. (axiom label in BFO2 Reference: [019-002])

**Comment by tucotuco** [comment]
I feel that reverting to 2) is a step backwards. I think we have evolved forward with four new suggestions, each of which builds on the previous one. What is the reason to go back to 2)?

**Comment by cboelling** [comment]
@tucotuco:

> I feel that reverting to 2) is a step backwards. I think we have evolved forward with four new suggestions, each of which builds on the previous one. What is the reason to go back to 2)?

On closer inspection, I don't see (3) as a step forward compared to (2), as evidenced by this discussion. Except for the specific suggestion [in your post](https://github.com/tdwg/material-sample/issues/34#issuecomment-1411086539) I understand the contributions in this thread as thoughts to achieve more clarity rather than specific suggestions for a re-phrasing of the definition - but maybe I have misunderstood. From this perspective, I think that (2) already encompasses the notion of identifiability, as pointed out by @smrgeoinfo, @Jegelewicz and @dagendresen above.

**Comment by Jegelewicz** [comment]
I find this to have the same meaning as 2, but to be much more approachable:

A material entity `can be identified`, exists for some period of time, and consists in whole or in part of physical matter while it exists.

**Comment by tucotuco** [comment]
I agree that is much more "approachable". I would suggest following the existing Darwin Core definition pattern, which defines rather than describes. Just for consistency. Here is an example of what I mean:

"An entity that can be identified, exists for some period of time, and consists in whole or in part of physical matter while it exists.

**Comment by tucotuco** [comment]
My same suggestion would apply to option 2) above, if that turns out to be preferred. Here is how I would adjust 2):

"An identifiable entity that persists, maintains its identity through some period of time, and consists in part or whole of some portion of matter at any given time of its existence."

As an aside, I find "that persists, maintains its identity through some period of time" to be redundant.

**Comment by Jegelewicz** [comment]
> An entity that can be identified, exists for some period of time, and consists in whole or in part of physical matter while it exists.

I vote for that as being more approachable...

**Comment by cboelling** [comment]
The rationale for creating `dwc:MaterialEntity` and the corresponding definition (2) is to create a top-level term in the Darwin Core namespace that is essentially equivalent to `bfo:MaterialEntity` while retaining full control over the term, including the ability to assert formal relations between both terms. Thus the rationale for the initially proposed definition (2) was to basically reiterate the BFO definition without its technicalities (to make it more "approachable", if you will). The original definition of `bfo:MaterialEntity`, applying the standard _genera/differentia_ structure of definitions, makes reference to other BFO elements which have their own definition. I find that combining this into one tractable standalone definition while retaining the rigour and context of the original definition is a bit of a challenge. In particular, instances of `dwc:MaterialEntity` are meant to be _continuants_, i.e. entities that can undergo significant changes in structure or composition while _persisting through time maintaining their identity_. This means they exist _fully_ (notwithstanding changes in structure or composition) at any given point in time. This is, in the BFO world, in contrast to _processes_ which are extended in time also, but exist fully only when seen over the complete time interval of their existence. The developing bird embryo inside a bird's egg is a _continuant_ (and a `bfo:MaterialEntity`). Egg incubation (more precisely: an instance of an Egg Incubation) is a _process_.

After the TG's decision on the final version of the definition from the proposals above, I will update [the corresponding NTR in the DwC repo](https://github.com/tdwg/dwc/issues/426) accordingly.

**Comment by Jegelewicz** [comment]
With February 12 fast approaching, we need to come together around a definition. I think there are currently two options from which to choose:

1.  An identifiable entity that persists and maintains its identity through some period of time, and consists in part or whole of some portion of matter at any given time of its existence.
2. An entity that can be identified, exists for some period of time, and consists in whole or in part of physical matter while it exists.


I prefer the second for it's simplicity and I also think that "that persists, maintains its identity through some period of time" is redundant. I find that "maintains its identity through some period of time" is sufficient.

**Comment by smrgeoinfo** [comment]
+1 for definition 2

**Comment by cboelling** [comment]
The majority view that appears to be forming is that option 2 from [the posting above](https://github.com/tdwg/material-sample/issues/34#issuecomment-1424362216) should be used as definition for `dwc:MaterialEntity`. Please confirm (perhaps after today's TG meetings which I unfortunately will not be able to attend) when this decision is final and when [the current term request](https://github.com/tdwg/dwc/issues/426) (which was initiated after the end of the initial TG-internal review period) should be updated accordingly.

**Comment by RogerBurkhalter** [comment]
+1 for definition 2 as well

**Comment by Jegelewicz** [comment]
Task Group agrees to use second definition.

@cboelling can you modify the new term request?

**Comment by cboelling** [comment]
[New Term Request](https://github.com/tdwg/dwc/issues/426) has been updated accordingly. Closing this issue.

**Comment by Jegelewicz** [comment]
Thank you @cboelling !
