### ISSUE TITLE
New term - materialEntityID

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#35]
The task group has agreed that we need to include materialEntityID in a package of terms with MaterialEntity. We also agreed that our previous work thinking about materialSampleID could be applied to this new term.

**Comment by Jegelewicz** [comment]
See new term proposal [here](https://github.com/tdwg/material-sample/blob/main/primary_deliverable/materialEntityID.md).

**Comment by Jegelewicz** [comment]
Please discuss the new term proposal for materialEntityID in this issue. I think the term and definition is fairly straightforward, but the other sections of the proposal probably need to some review by people with TDWG knowledge. @tucotuco @stanblum @baskaufs

**Comment by dagendresen** [comment]
The [new term description](https://github.com/tdwg/material-sample/blob/main/primary_deliverable/materialEntityID.md) includes
> ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

Could the `materialEntityID` maybe be mapped to ABCD 2.06 [Unit/UnitGUID](Unit/UnitGUID) or [Unit/UnitID](https://abcd.tdwg.org/xml/documentation/ABCD_2.06/ABCD_2_06_xsd.html#Unit_UnitID
) (or would we here rather think of the `ABCD Unit` as more a sort of analogue of the sub-class `PreservedSpecimen` than an analogue of the MaterialEntity?)

**Comment by tucotuco** [comment]
@dagendresen MaterialEntity identifiers would go into those two places in ABCD, so I think those are good mapping. Are they more places MaterialEntity identifiers might go in ABCD?

**Comment by baskaufs** [comment]
I read through it and don't see any glaring problems.

**Comment by tucotuco** [comment]
I made [some edits](https://github.com/tdwg/material-sample/commit/d2c3edc20032760b41a27ebcff680d307f733f8e). Based on timing, it looks like @baskaufs  probably looked at the edited version, but maybe should confirm that.

**Comment by baskaufs** [comment]
Yes, it was the edited version.

**Comment by Jegelewicz** [comment]
At TG meeting today all participants agreed this is fine and can be add to the package.

**Comment by Jegelewicz** [comment]
Need to write up proposal.

**Comment by Jegelewicz** [comment]
Added to review package - https://github.com/tdwg/material-sample/blob/main/review%20package/materialEntityID.md

**Comment by Jegelewicz** [comment]
change complete - https://github.com/tdwg/dwc/issues/455
