### ISSUE TITLE
Review proposed term - vitality

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#36]
A new term is being proposed in the current Darwin Core review package - [vitality](https://github.com/tdwg/dwc/issues/363)

Members of the task group are asked to review this proposal and add comments if it appears that the term could also be useful for material. People seem to care deeply about the alive/dead status of things in collections and we should consider whether this term could be a useful property of material as proposed.

**Comment by deepreef** [comment]
I've been off-grid for over a month, so am woefully out of the loop.  However, the distinction of "alive/dead" seems to me to be a property of Organism, not so much of a material thing.  This gets at the heart of the line between MaterialSample/MaterialEntity and Organism.  Whether or not an Organism is alive or dead is much more a question of energy, than it is of matter, in my view.

**Comment by deepreef** [comment]
And just to clarify, because aliveness/deadness is a function of Organism-at-time (rather than Organism per se), I think it's rightfully organized in the Occurrence class.  But for reasons already stated, I don't think it has much bearing on the material-ness class(es).

**Comment by Jegelewicz** [comment]
But how does that square with LivingSpecimen?

**Comment by deepreef** [comment]
I've never liked the LivingSpecimen/PreservedSpecimen distinction in the MaterialSample context, But having been out of the loop for so long (travel, etc.), I'm still not caught up on what the implications for MaterialEntity/ID are with respect MaterialSample, LivingSpecimen, PreservedSpecimen, FossilSpecimen, etc.

My general feeling is that we don't need separate classes for all these things.  My hope is that MaterialEntity/ID is simply a replacement term for MaterialSample/ID, and that with the new term we can clearly define it in the context of physical matter.  That would help distinguish it from Organism (which involves more than just physical matter).

But as I said, I'm out of the loop and need to catch up on all the MaterialEntity stuff.

**Comment by Jegelewicz** [comment]
> My general feeling is that we don't need separate classes for all these things. My hope is that MaterialEntity/ID is simply a replacement term for MaterialSample/ID, and that with the new term we can clearly define it in the context of physical matter. That would help distinguish it from Organism (which involves more than just physical matter).

That sums it up for me too.

**Comment by deepreef** [comment]
Cool!  My thinking is:
- `Location`: defined footprint on planet Earth (or other celestial bodies?)
- `Event`: Some sort of action or happening that takes place at a `Location` within some defined period of time (with properties of who, how, etc.)
- `Organism`: Abstract biological and taxonomically homogenious entity consisting of one or more individuals persisting over a period of time (e.g., from birth to death).
- `Occurrence`: Intersection of an `Organism` with an `Event`, with associated properties relating to that intersection.
- `Taxon`: Defined or implied circumscription of Organisms, representing taxonomic homogeneity among the circumscribed set of organisms.
- `Identification`: Intersection of an `Organism` and a `Taxon`, with associated properties relating to that intersection.
- `MaterialEntity`: Physcial matter that can serve as objects of interest/curation/etc., as well as functioning as Tokens/Evidence in support of instances of `Occurrences` and `Identifications` (and others?)
- `MaterialCitation`: Documentation (e.g., publication) functioning as Tokens/Evidence in support of instances of `Occurrences` and `Identifications` (and others?)
- `MeasurementOrFact`: A mechanism to associate literal property values to any instance of the above classes, not already represented by a defined DwC term.
- `ResourceRelationship`: A mechanism to associate any instance of the above classes with any other instance of the above classes, with associated properties of that association.
- `Record-level`: a bag of terms that could apply to any of the above classes.
- `UseWithIRI`: A system to explicitly represent values of certain terms within DwC space as resolvable identifiers.

I don't have a lot of experience with `GeologicalContext`, but I wonder if this class isn't essentially a subclass of `Event`?

As for the other DwC "classes":
- `LivingSpecimen`
- `PreservedSpecimen`
- `FossilSpecimen`
- `HumanObservation`
- `MachineObservation`
...these seem much less to me like "classes", and would be better represented as values in a controlled vocabulary as applied to terms in one of the "real" classes above.

Note that my description above is pretty much in line with both [Darwin-SW](https://github.com/darwin-sw/dsw) and the data model Rob Whitton and I developed as part of the old NSF-funded BiSciCol project.  I see `MaterialEntity` and `MaterialCitation` as two of the four main types of things we (Rob and I) considered as "Evidence" (which I thing is functionaly similar to or the same as "Token" in DSW).  The other two are essentially "Media" (i.e., Audubon/Audiovisual Core space), and "Observation" (i.e., cases where the only available evidence is that someone asserts it, without physical, media, or documented evidence to support the assertion).

Not sure why I took the time to regurgitate all of the above, so apologies for the digression.  But I was hoping to help clarify the context in which I see the need for the `MaterialEntity` class in DwC, and perhaps explain where I'm coming from regarding my views on where `vitality` might fit in.

**Comment by Jegelewicz** [comment]
Task Group agrees this is pertinent to Organism and out of scope.

**Comment by tucotuco** [comment]
I do not agree with the conclusion that vitality is a persistent property of an Organism. It is a property of the Organism at a particular place and time (an Event). Happily, it is not a property of a MaterialEntity, so it has no further bearing in the scope of the Task Group and closing the issue seems a fine solution.

**Comment by deepreef** [comment]
> I do not agree with the conclusion that vitality is a persistent property of an Organism. It is a property of the Organism at a particular place and time (an Event). Happily, it is not a property of a MaterialEntity, so it has no further bearing in the scope of the Task Group and closing the issue seems a fine solution.

I agree.  Also, Organism at Event = Occurrence [yes, it is still a "thing"!]  So vitality, like behavior, sex, and various other properties that do not remain constant over the lifespan (sensu lato) of an Organism are properly organized within the Occurrence class.

**Comment by Jegelewicz** [comment]
I didn't say persistent, I said pertinent....

**Comment by tucotuco** [comment]
True, but if it is not persistent, then it is not a particularly good candidate for a property.

**Comment by stanblum** [comment]
> It is a property of the Organism at a particular place and time (an Event). Happily, it is not a property of a MaterialEntity[...]

I agree that dwc:vitality is a property of of an Organism in an Event, but because most specimen collections don't explicitly create an organism instance separate from the MaterialEntity instance (i.e., PreservedSpecimen), it is appropriate to include a vitality property of the organism when it was collected and became a specimen. And I believe that's the context assumed by How-did-it-die task group.
