### ISSUE TITLE
Definition of materialSample

### ISSUE THREAD

**Issue by smrgeoinfo** [tdwg/material-sample#37]
With the adoption of MaterialEntity and usage comment "In particular, any kind of material sample, .... is intended to be subsumed by this term.", it seems that the proposed definition of materialSample should be updated to replace "physical object".  Could also simplify then by takeing 'physical' modifier out of 'entity of interest' to read

`A material entity that represents an entity of interest in whole or in part.`

**Comment by dr-shorthair** [comment]
Yes

**Comment by Jegelewicz** [comment]
Added change to review packacge
