### ISSUE TITLE
Enhancement - references

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#38]
from @tucotuco 

> other terms for which adoption of MaterialEntity will require non-normative changes. These include the following:
> 
> references (has an example MaterialSample that should become a MaterialEntity)
>

**Comment by smrgeoinfo** [comment]
I'm still unclear on whether MaterialEntity replaces MaterialSample, or we recognized that MaterialSample is a particular kind of MaterialEntity, based on the sampling intention.  If its the second case, the references example doesn't need to change, and seems perfectly valide.

**Comment by cboelling** [comment]
> MaterialSample is a particular kind of MaterialEntity

This is the case (possible limitations of DwC to specify subclass relations aside).

**Comment by baskaufs** [comment]
I think the situation is that MaterialEntity does not replace MaterialSample. So people could certainly still use it. However, given that MaterialEntity is a more broadly usable term and doesn't contain some of the baggage of MaterialSample, it might still be advisable to replace MaterialSample in the example.

**Comment by deepreef** [comment]
I know I've asked this before, and I *think* I understand the idea that `dwc:MaterialSample` remains a "thing" and is to be treated as a subclass of the broader class of instances of `dwc:MaterialEntity`.  Presumably, that subclass would be (more or less) defined as "the subset of `dwc:MaterialEntity` instances that represent the products of a sampling action" (or something like that)?  If that's the case, I think it would be helpful to identify which properties apply only to the MaterialSample subclasses of MaterialEntity instances.  I can imagine a few, but I'm not confident enough in my own understanding of the boundary between a `MaterialSample` subclass and instances of `MaterialEntity` that do not fall within that subclass, or (presumably) other (mutually-exclusive? overlapping?) subclasses of `MaterialEntity`.

I also understand that there would be a clean 1:1 equivalency of values of `materialSampleID` and `materialEntityID`, when presenting either or both with instances that belong to the `MatrerialSample` subclass through as a shared data resource.

**Comment by smrgeoinfo** [comment]
MaterialSample "the subset of dwc:MaterialEntity instances that are intended to represent some aspect of a MaterialEntity" (or something like that. So a MaterialSample has a sampledMaterialEntity (lots of other possible labels).
Specimen "the subset of dwc:MaterialEntity instances that are included in a collection by some agent" (or something like that).

**Comment by stanblum** [comment]
I'm going to slice things very finely here, but (@smrgeoinfo) that's not the way I understand subtyping/subclassing to work in Entity-Relationship and Object Oriented modeling (perhaps others).  The way I understand those methodologies and the way I understand our result, a MaterialSample is a kind of MaterialEntity, so a MaterialSample `is_a` MaterialEntity.  They aren't different instances.  If you wanted to indicate which MaterialEntity was sampled and is now represented as a MaterialSample, then the `has_a` or `represents` relationship would be appropriate, and they would be different instances.

**Comment by dagendresen** [comment]
> helpful to identify which properties apply only to the MaterialSample subclasses of MaterialEntity instances

Could we not think of MaterialSample similar as we think of PreservedSpecimen etc, and not align any properties specifically to MaterialSample (sufficiently to align properties indirectly to the super-class MaterialEntiry)?

**Comment by deepreef** [comment]
> Could we not think of MaterialSample similar as we think of PreservedSpecimen etc, and not align any properties specifically to MaterialSample (sufficiently to align properties indirectly to the super-class MaterialEntiry)?

I'm wondering if we need any of those terms at all (MaterialSample, PreservedSpecimen, LivingSpecimen, FossilSpecimen), except perhaps as values in a controlled vocabulary as some sort of property of MaterialEntity.  It seems like overkill to maintain them as subclasses; especially when they might not even be mutually exclusive.

**Comment by Jegelewicz** [comment]
> I'm wondering if we need any of those terms at all (MaterialSample, PreservedSpecimen, LivingSpecimen, FossilSpecimen), except perhaps as values in a controlled vocabulary as some sort of property of MaterialEntity. It seems like overkill to maintain them as subclasses; especially when they might not even be mutually exclusive.

My answer - these should be deprecated and new properties for the MaterialEntity class should be created in order that users of data can separate out fossils, from living things, from "recently dead and preserved things", from "recently dead things that we generated information from but that were discarded or used up in the process"; BUT that is a project for the next task group or we will never accomplish anything!

**Comment by deepreef** [comment]
Thanks, @Jegelewicz!  I understand, and completely agree (on all points).

**Comment by Jegelewicz** [comment]
change complete - https://github.com/tdwg/dwc/issues/456
