### ISSUE TITLE
Primary Deliverable - LivingSpecimen definition

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#4]
## Current Definition

http://rs.tdwg.org/dwc/terms/LivingSpecimen

> A specimen that is alive.

Please suggest changes/improvements in this issue.

See also https://github.com/tdwg/material-sample/blob/main/primary_deliverable/LivingSpecimen.markdown

**Comment by Jegelewicz** [comment]
The current definition indicates that this is a sublcass of **specimen**. A term NOT included in Darwin Core.

The [BCO](http://www.ontobee.org/ontology/BCO?iri=http://rs.tdwg.org/dwc/terms/LivingSpecimen) indicates that this is a subclass of both [specimen](http://www.ontobee.org/ontology/BCO?iri=http://purl.obolibrary.org/obo/OBI_0100051) and its equivalent term [Material Sample](http://www.ontobee.org/ontology/BCO?iri=http://rs.tdwg.org/dwc/terms/MaterialSample) which is associated with Darwin Core MaterialSample. 

Given this, it seems to me that LivingSpecimen is a subclass of MaterialSample and a more appropriate definition would be:

**A MaterialSample that is alive.**

But this just feels odd. My gut feeling is that "living specimen" is a somewhat uncomfortable term. Will zoos use this term? If we end up meshing data with human collections, would individuals in a clinical trial be referred to as "living specimens"?

For me, there are no "living specimens". These are simply organisms or entities. We may make observations of them or even take MaterialSamples from them, but even if they are held captive, referring to them as "specimens" feels wrong.

**Comment by dagendresen** [comment]
There is also the use case of living specimen "accessions" or "seed samples" in a seedbank collection (and microbes in a microbial culture collection). In [another GitHub thread](https://github.com/tdwg/dwc/issues/302#issuecomment-720133126), Rich suggested positively intriguingly that in field trial experiments with such seed samples they could be seen as Occurrences of Organisms observed _ex situ_. The living seed samples typically are assigned catalog numbers and treated much like other specimens. -- Is it in any way possible for the seed samples to be both a MaterialSample (inside in the seed collection) and an Organism (outside in the field trials)??

**Comment by tucotuco** [comment]
Additional related commentary in https://github.com/tdwg/material-sample/issues/3#issuecomment-903305155.

**Comment by afuchs1** [comment]
examples of catalogued accessions we currently treat as "LivingSpecimen" - plants in the Botanic Gardens, seed/germplasm in a seed bank. Other examples are living 'aglae' collections. Currently we treat seed in a germination trial (generally in the lab) as a LivingSpecimen and it will have a disposition of 'deaccessioned' when the trial is completed and a cut-test renders it no longer viable. The way in which "LivingCollection" accessions relate together are held as relationships - propagated from|parent of| etc.

**Comment by smrgeoinfo** [comment]
see https://github.com/tdwg/material-sample/issues/3#issuecomment-908726472

**Comment by Jegelewicz** [comment]
The Task Group has decided to deprecate this term and perhaps integrate it into controlled vocabulary for materialSampleType. This is a draft of the dwc issue to submit.

## Term change

* Submitter: TDWG MaterialSample Task Group
* Efficacy Justification (why is this change necessary?): Deprecate this term for consolidation of physical objects into the class MaterialSample rather than including specific classes for different kinds of physical objects which can be covered under materialSamplType
* Demand Justification (if the change is semantic in nature, name at least two organizations that independently need this term): 
* Stability Justification (what concerns are there that this might affect existing implementations?): 
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: Yes

Current Term definition: https://dwc.tdwg.org/list/#dwc_LivingSpecimen

Proposed attributes of the new term version (Please put actual changes to be implemented in **bold** and ~strikethrough~):

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): ~LivingSpecimen~
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): 
* Definition of the term (normative): ~A specimen that is alive.~
* Usage comments (recommendations regarding content, etc., not normative): 
* Examples (not normative): ~A living plant in a botanical garden. A living animal in a zoo.~
* Refines (identifier of the broader term this term refines; normative): 
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): 
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative):

**Comment by Jegelewicz** [comment]
Based upon requested change in the MaterialSample definition change and taking the opportunity to make this definition more than an extended version of the term. I will add a revised definition for this term to the review package.

## Current Definition
LivingSpecimen - A specimen that is alive.

## Proposed Definition
LivingSpecimen - A material entity that represents an entity of interest in whole or in part that has the capacity for growth, reaction to stimuli, or active metabolism.

**Comment by cboelling** [comment]
With respect to the newly proposed definition:

On the premise that _"represents an entity of interest in whole or part"_ is intended to capture the _specimen role_ of the material entity in question and that _"has the capacity for growth, reaction to stimuli, or active metabolism"_ is intended to capture what it means to be alive, I would switch positions of these clauses in the definition. For me this is easier to read and understand:

LivingSpecimen - A material entity that has the capacity for growth, reaction to stimuli, or active metabolism and that represents an entity of interest in whole or in part.

**Comment by Jegelewicz** [comment]
@cboelling should we do the same for the other three? (FossilSpecimen, PreservedSpecimen, Material Sample)? I'd like to keep these as consistent as possible.

**Comment by cboelling** [comment]
> @cboelling should we do the same for the other three? (FossilSpecimen, PreservedSpecimen, Material Sample)? I'd like to keep these as consistent as possible.

I would say yes - for `dwc:MaterialSample` this isn't an issue because in its definition only the sample role is expressed, but for the other two I find that swapping the clauses makes these definitions more readable.

Disclaimer: I have not, on this occasion, reviewed other possible implications of the proposed definitions, i.e. if the implicit definition of _alive_ or the reference to _current_ or _past_ geological ages are adequate for the purpose of giving definitions for the respective DwC terms. This comment is only about the sentence structure of these new proposals.

**Comment by baskaufs** [comment]
See my comment [here](https://github.com/tdwg/material-sample/issues/3#issuecomment-1534922644) about my issue with the specimen definitions. 

The problem I raise is particularly relevant here. As the definition currently stands, there is no way to differentiate between random plants that I photograph in the wild and actual living specimens in a botanical garden or arboretum. Both are "entities of interest", but the plants in the wild are not specimens. The definition needs to include "in a collection" or something similar to differentiate between the two.

**Comment by Jegelewicz** [comment]
@baskaufs would this work?

LivingSpecimen - A material entity that represents an entity of interest in whole or in part that is curated in a collection and has the capacity for growth, reaction to stimuli, or active metabolism.

**Comment by smrgeoinfo** [comment]
Given that the criteria for 'specimen' is 'material entity in a collection', the 'represents an entity of interest' is not part of the definition. 

A material entity in a collection that has the capacity for growth, reaction to stimuli, or active metabolism.
