### ISSUE TITLE
Other Deliverable - disposition review

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#8]
> Task Group will make a recommendation [...] as to which class in the Darwin Core standard these properties belong which may also include recommendations for terms being revised, added, disambiguated, or deprecated. Depends upon definitions provided [in primary deliverable].

# Current Darwin Core Placement/Definition

http://rs.tdwg.org/dwc/terms/disposition

this term is a **property** of **Occurrence**

## Defintion
The current state of a specimen with respect to the collection identified in collectionCode or collectionID.

## Examples
in collection, missing, voucher elsewhere, duplicates elsewhere

## Comments
Recommended best practice is to use a controlled vocabulary.

##See also
Change term - disposition: https://github.com/tdwg/dwc/issues/347

**Comment by smrgeoinfo** [comment]
This is currently defined as the 'current state of a specimen'.  A specimen is (as I understand it) a subclass of materialEntity that was collected for some purpose, typically as representative of some feature in the world we want to study.  Since a 'particular pack of wolves' is listed as an example of materialEntity, would the scope of 'disposition' include the disposition of the pack? what would that mean?  
Expanding the view, note that according to our definition, any identifiable material object is a materialEntity-- the sun, moon, White House, Mount Everest.  Do these have dispositions?  
Seems like disposition is property of a sample/specimen, not materialEntity in general.

**Comment by Jegelewicz** [comment]
> Do these have dispositions?

Yes!

The White House is a building in the "collection" of the government of the United State of America and its disposition could be a lot of things, including "in collection", or "on loan" to Joeseph Biden?

As with preparations, the use of 'specimen' which really does not have a universally agreed-upon definition makes some people see this term in a certain way and assume that only things that were obtained for a specific purpose will be described with the term.

A change to

`The current state of a ~~specimen~~ **MaterialEntity** with respect to the collection identified in collectionCode or collectionID.`

Allows for much broader use of the term.

**Comment by stanblum** [comment]
Do these have dispositions?
>
> Yes!
> The White House is a building in the "collection" of the government of the
> United State of America and its disposition could be a lot of things,
> including "in collection", or "on loan" to Joeseph Biden?

I think those interpretations of collection and disposition are stretched
too far.  In DwC the definition is explicitly within the context of a
collection, and government buildings are not "collected" the way that art,
cultural, historical, library, and scientific collections are built and
managed. In all of "our" kinds of collections, the domain of "disposition"
(possible values) would be pretty similar, but would have much less overlap
with the possible dispositions of government buildings.  In the DwC, only
collected materialEntities can have that kind of disposition.  (The White
House is "occupied by" or "legal residence of", not "on loan to", Joe and
Jill Biden.)

But more to the point (where does "disposition" fit among the classes we're
talking about?), dwc:disposition could be a property of several "kinds" of
materialEntity, but not all materialEntities.

I think help us to be clear on this more general principle of information
architecture:  If a property is applicable to more than one subclass, does
that mean it should be "attached" higher up -- to the containing superclass
-- or should be be applied only where it makes sense?  My guess is that
"only where it makes sense" would be the ontological answer.  Can anyone
else answer that question?

**Comment by dagendresen** [comment]
However, Darwin Core is not an ontology, and where a term is "organized" is not designed to carry any ontological meaning.

**Comment by tucotuco** [comment]
>But more to the point (where does "disposition" fit among the classes we're talking about?), dwc:disposition could be a property of several "kinds" of materialEntity, but not all materialEntities. I think help us to be clear on this more general principle of information architecture: If a property is applicable to more than one subclass, does that mean it should be "attached" higher up -- to the containing superclass -- or should be be applied only where it makes sense? My guess is that "only where it makes sense" would be the ontological answer. Can anyone else answer that question?

In the context of class hierarchies, the property should be at the highest level class whose children all share the need for the property. We don't have formal class hierarchies, but if we ignore that formality and imagine what the hierarchy would look like for the classes we have MaterialEntity as the highest for material things. All of the other material-based classes we have (PreservedSpecimen, FossilSpecimen, LivingSpecimen, MaterialSample) would be good candidates for having dispsitions. We don't have any other classes in between MaterialEntity and those subtypes, so disposition would have to go with the MaterialEntity. 

As @dagendresen says, we don't have a hierarchy and we are not making any ontological entailments by having a term "organized in" a particular class. That organization is informal and determines where the property appears a) on the Darwin Core Quick Reference Guide, b) on the Darwin Core lists of terms, c) in the field mappings sections in the Integrated Publishing Toolkit. It basically helps humans to have some context about what it refers to.

**Comment by cboelling** [comment]
> I think help us to be clear on this more general principle of information architecture: If a property is applicable to more than one subclass, does that mean it should be "attached" higher up -- to the containing superclass -- or should be be applied only where it makes sense? My guess is that "only where it makes sense" would be the ontological answer. Can anyone else answer that question?

The approach to "attach" properties (aka attributes) to the highest level within a class hierarchy and let subclasses *inherit* those properties is an approach routinely used in object-oriented modelling and application development, and also (for the former) in standard relational database design. It could be characterized as a closed-world approach to knowledge engineering where anything that is to say about a resource is confined to the properties that have been declared. In such approaches, using a property in the context of a class for which it hasn't been declared is non-sensical and illegal from the point of view of the application.

Open World Approaches (like RDF and OWL) treat properties as first class citizens - they are *not* defined for a specific class, but there could be entailments in terms of ranges and domains which allocate a given individual to a class if it is used in a statement with that property. This approach has often been characterized as one in which information about a subject is generally regarded as potentially incomplete.

Strictly speaking, on the level of the DwC standard none of this should be relevant as it is maintained as a flat terminology without formal relations between the terms.  However, property terms *are* in fact being related to individual class terms in DwC. This relation is variously being described as *informal*, *organizational* and as a pragmatic means to structure the presentation of the terminology on the websites that describe the standard. In the current practice of DwC creation, usage and maintenance, however, it seems to me that the prevailing mindset that is brought to bear on DwC is oriented towards the object-oriented approach: A property term that is "organized" in the context of a given class term in the DwC resources is expected to be used as an attribute for instances of this class and only this class.

For a setting in which a very general term that stands for a very wide class of things (like `dwc:MaterialEntity`) is complemented by a likely growing number of terms which effectively stand for subclasses of the former and may have hierarchies and overlaps of their own, a mindset that actually treats property terms as independent from class terms (as is *actually* the case in DwC!) might be more effective.

With respect to `dwc:disposition` I think the examples make clear the intended usage of the term. It is a very specific meaning of the word "disposition" with respect to the availability of an artefact in a collection. I think that the definition should be changed to reflect this intent.

And yes, the kind of states that `dwc:disposition` appears to be intended for can be meaningfully assumed only by certain collection objects, but not the *White House* (as a building complex) or the *sun*, but all of them are MaterialEntities. An approach in which properties are first class citizens and needn't be attached to defined classes that *exactly* correspond to their domain can significantly simplify matters.

As an aside: I'm not sure if the notions of *class* and *property* are formally defined in DwC either.

**Comment by tucotuco** [comment]
> As an aside: I'm not sure if the notions of _class_ and _property_ are formally defined in DwC either.

They are. See, for example,

https://dwc.tdwg.org/list/#dwc_MaterialSample and https://github.com/tdwg/dwc/blob/590c0720e228537274d55d25d996ccf66d68e3ae/vocabulary/term_versions.csv#L55

and

https://dwc.tdwg.org/list/#dwc_materialSampleID and https://github.com/tdwg/dwc/blob/590c0720e228537274d55d25d996ccf66d68e3ae/vocabulary/term_versions.csv#L56

**Comment by baskaufs** [comment]
> A property term that is "organized" in the context of a given class term in the DwC resources is expected to be used as an attribute for instances of this class term and this class term only.

I guess I would agree with the first part of this ("expected to be used as an attribute for instances of this class term") but not the second ("and this class term only"). I think that there is a recognition that there may be different modeling choices that would result in a property being used with instances of a class different than the one under which a property is organized. This certainly happens when more complex models are "flattened" by users who don't need the complexity of a more normalized model for their use cases.

> I'm not sure if the notions of class and property are formally defined in DwC either.

Actually it is. The Standards Documentation Specification, which applies to all TDWG vocabularies, says in [Section 4.5](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#45-metadata-properties-for-describing-vocabulary-terms) that "Types SHOULD be rdf:Property for properties, rdfs:Class for classes, and skos:Concept for controlled values."

**Comment by Jegelewicz** [comment]
> a mindset that actually treats property terms as independent from class terms

I am trying very hard to keep to this mindset, but it is difficult when

> there is a recognition that there may be different modeling choices that would result in a property being used with instances of a class different than the one under which a property is organized. 

doesn't seem to be universally recognized and until such time that some property is "organized" under more than one class, I don't think it is obvious.

**Comment by Jegelewicz** [comment]
BUT back to this term. As I see it, there are definitely MaterialEntity instances that COULD be part of a collection and this seems like an appropriate property for MaterialEntity, regardless if it is also a property for other classes in Darwin Core. Perhaps a better definition would make that clear?

The current state of ~~a specimen~~ an instance of a Darwin Core class with respect to the collection identified in collectionCode or collectionID.

**Comment by stanblum** [comment]
So, where I was going with this:  

IF 
- some materialEntitys don't have dwc:disposition, and all the "specimen" classes do [dwc:LivingSpecimen, dwc:PreservedSpecimen, dwc:FossilSpecimen; as well as whatever we end up replacing dwd:MaterialSample with]

THEN
- there is an implied subclass, "collected MaterialEntity."

I think people trying to understand DwC on the basis term-names and standard dictionary definitions would understand "collected material entities" and "material samples" to be more or less equivalent, and all our specimens to be kinds of material samples; i.e., subclasses of materialSample.

@smrgeoinfo 's diagram represents my world view REALLY well.  ![](https://user-images.githubusercontent.com/513380/213515502-d5b0dc97-4ab4-49c8-840e-0d368ad0d7ee.png) 

We can organize dwc:disposition under MaterialEntity **(I'm OK with that)**, but the more accurate place to put it would be under MaterialSample. The problem with that solution is the existing usage/understanding of MaterialSample to be the "right" class for genetic resources (Tissue Samples, DNA Extracts, Environmental Samples).  And we're not creating subclasses...  :-( 

As parents say to children, "use your words"; or when you get older, [express yourself](https://www.youtube.com/watch?v=rImQZ8euKok)   :-)

**Comment by smrgeoinfo** [comment]
There are materialEntities for which 'dwc:disposition' is not applicable.
From the existing definition, it seems reasonable to infer that materialEntity that is a member of a dwc:collection can have a 'disposition'. 
`The current state of a dwc:materialEntity that is a member of a dwc:Collection.`

**Comment by dagendresen** [comment]
I prefer to keep "_specimen_" for reasons described well by Stan (but is less certain of the word "_state_", might "_current disposition state_" be more precise?)
> The current `state` of a `specimen` with respect to the collection identified in collectionCode or collectionID.

Apropos, for germplasm collections, we would most often have both "`in collection`" AND "`duplicates elsewhere`". (Best practice is for ALL germplasm specimens to be both available from the `in collection` instance AND safety duplicated at Svalbard. I guess I wonder what "duplicates elsewhere" actually mean?).

> Examples: in collection, missing, voucher elsewhere, duplicates elsewhere

See e.g. the [FAO Multi-Crop Descriptor DUPLSITE](https://hdl.handle.net/10568/69166)
> 25. Location of safety duplicates (DUPLSITE)
> FAO WIEWS code of the institute(s) where a safety duplicate of the accession is maintained.
Multiple values are separated by a semicolon without space. Follows INSTCODE standard.

**Comment by dagendresen** [comment]
Even if the discussion about _"organized in class"_ above probably belong elsewhere than this issue, I want too much to make a brief comment.

> However, property terms are in fact being related to individual class terms in DwC
> A property term that is "organized" in the context of a given class term in the DwC resources is expected to be used as an attribute for instances of this class term and this class term only.

When terms "organized" under different classes are used in a [Simple Darwin Core](https://dwc.tdwg.org/simple/) record (and other denormalized usages of DwC terms) most often these terms are not intended to be seen as a property of the respective class instance of this record but intended to indicate that there exists an inferable instance of the other class that these terms are "organized" under in DwC. When scientificName, vernacularName (etc) is used in a Simple DwC record - this does not intend to mean that the species Occurrence has this name, but that there exists an inferable instance of the Taxon class that has this name. And the ID-terms, taxonID, institutionID, collectionID, materialSampleID, etc, do not intend to mean that these are identifiers identifying the actual species Occurrence instance (see also [DwC RDF guide about ID terms here](https://dwc.tdwg.org/rdf/#26-darwin-core-id-terms-and-rdf-normative)). Etc...

**Comment by Jegelewicz** [comment]
>  terms are not intended to be seen as a property of the respective class instance of this record but intended to indicate that there exists an inferable instance of the other class that these terms are "organized" under in DwC

I would never in a million years have thought that! "Infer" seems like something we wouldn't want to be doing here? Sorry if I am being dense, but that just sounds like trouble.

**Comment by dagendresen** [comment]
Agree, Darwin Core is not an ontology and does not support formal semantic inference. Of lack of a better word maybe "... _indicate that there exists an instance of the other class_" for which the property is attached.

**Comment by Jegelewicz** [comment]
Make a property of Material Entity, change definition to

`The current state of a MaterialEntity with respect to a collection.`

**Comment by Jegelewicz** [comment]
changes to examples

in collection, missing, on loan, used up, destroyed, deaccessioned

**Comment by Jegelewicz** [comment]
added to review package - https://github.com/tdwg/material-sample/blob/main/review%20package/disposition.md

**Comment by Jegelewicz** [comment]
change complete - https://github.com/tdwg/dwc/issues/453
