### ISSUE TITLE
Other Deliverable - associatedSequences review

### ISSUE THREAD

**Issue by Jegelewicz** [tdwg/material-sample#9]
> Task Group will make a recommendation [...] as to which class in the Darwin Core standard these properties belong which may also include recommendations for terms being revised, added, disambiguated, or deprecated. Depends upon definitions provided [in primary deliverable].

# Current Darwin Core Placement/Definition

http://rs.tdwg.org/dwc/terms/associatedSequences

this term is a **property** of **Occurrence**

## Defintion
A  list (concatenated and separated) of identifiers (publication, global  unique identifier, URI) of genetic sequence information associated with  the Occurrence.

## Examples
http://www.ncbi.nlm.nih.gov/nuccore/U34853.1, http://www.ncbi.nlm.nih.gov/nuccore/GU328060 | http://www.ncbi.nlm.nih.gov/nuccore/AF326093

## See also
Change term - associatedSequences: https://github.com/tdwg/dwc/issues/332

**Comment by smrgeoinfo** [comment]
the ability to link to relatedResources should be a property of any entity; I'm not familiar enough with all of Darwin Core to know if that's already there.   Clearly there are many materialEntities that do not have associated  'genetic sequence information'.  A subclass of materialEntity could be defined to include entities that have genetic sequences (?biologicalEntity?)

**Comment by Jegelewicz** [comment]
> ability to link to relatedResources should be a property of any entity

I think the problem might be what class does 'genetic sequence information' belong to?

[ResourceRelationship](https://dwc.tdwg.org/terms/#resourcerelationship) is `A relationship of one rdfs:Resource (http://www.w3.org/2000/01/rdf-schema#Resource) to another.`

and

`Resources can be thought of as identifiable records or instances of classes and may include, but need not be limited to dwc:Occurrence, dwc:Organism, dwc:MaterialSample, dwc:Event, dwc:Location, dwc:GeologicalContext, dwc:Identification, or dwc:Taxon.`

I just don't see a class that sequence information belongs in and am feeling @albenson-usgs pain.

Or is a sequence a [MeasurementOrFact](https://dwc.tdwg.org/terms/#measurementorfact)?

It feels like `dwc:associatesSequences` was created simply because we don't have an "Identifier" or an "InformationArtefact" class?

> A subclass of materialEntity could be defined to include entities that have genetic sequences (?biologicalEntity?)

This would make me very sad - we already have at least four of those: Organism, MaterialSample, LivingSpecimen, PreservedSpecimen and perhaps even a fifth as FossilSpecimens can sometimes yield DNA.

**Comment by albenson-usgs** [comment]
I'm coming to this without the benefit of the last few task group meetings but I am puzzled by this statement "Clearly there are many materialEntities that do not have associated 'genetic sequence information'." I would put this term in the MaterialEntity class because I don't think it's necessary for every term organized into that class to _apply_ to every record or observation that might be documented in that class. As it stands now if I have an Occurrence that has an associatedReference then I populated that term with the corresponding information. If I have an Occurrence that does not have an associatedReference then I don't populate that term with any information. I'm confused why this wouldn't be possible if it was put in the MaterialEntity class?

**Comment by deepreef** [comment]
I am also lacking the benefit of recent meetings, and am slowly getting caught up on the GitHub commentary, but I just wanted to say that I completely agree with what @albenson-usgs says above.

**Comment by dagendresen** [comment]
Agree, however, I also do see the worry of @smrgeoinfo. If classes are sort of seen as defined by the terms organized under or grouped by the class. I know Darwin Core is only a bag of terms, but I think it is a valid thought for many to make even so. Would spicing the MaterialEntity class with the task or "organizing" (too many) terms that too clearly belong to biological things sort of alienate things that are more geological by nature? 

Would it harm to move associatedSequences (etc) to be organized under the Record-level terms? Or simply keep associatedSequences organized under Occurrence? 

Would be nice if we could also describe geology with Darwin Core...???

A bigger question could be if we actually want a new class for DNA Sequences in Darwin Core...???

**Comment by dagendresen** [comment]
The definition for associatedSequences states

> A list (concatenated and separated) of identifiers (publication, global unique identifier, URI) of genetic sequence information `associated with the Occurrence`.

We could propose to get rid of "_associated with the Occurrence_" or propose a change to "_associated with the subject_" or to something along "_associated with the Organism, Occurrence, MaterialEntity, Event, Location, or other subjects or interest_" :-)

**Comment by Jegelewicz** [comment]
> more geological by nature

DNA sequences can be taken from water and soil....

**Comment by Jegelewicz** [comment]
A list (concatenated and separated) of identifiers (publication, global unique identifier, URI) of genetic sequence information associated with the MaterialEntity.

**Comment by Jegelewicz** [comment]
added changes to review package https://github.com/tdwg/material-sample/blob/main/review%20package/associatedSequences.md

**Comment by Jegelewicz** [comment]
submitted to dwc repo - https://github.com/tdwg/dwc/issues/454

**Comment by Jegelewicz** [comment]
change complete - https://github.com/tdwg/dwc/issues/454
